### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by loringabriel** [WebDevSimplified/Machine-Learning-Color-Contrast-Picker#1]
https://github.com/WebDevSimplified/Machine-Learning-Color-Contrast-Picker/blob/eca505523c4e44ba08c0b92d3bb250a48331732e/index.html#L8

'http' is missing on line 8 :)

**Comment by VlatkoStojkoski** [comment]
This is not a typo.

Refer to: [StackOverflow](https://stackoverflow.com/questions/550038/is-it-valid-to-replace-http-with-in-a-script-src-http)
*"A relative URL without a scheme (http: or https:) is valid, per [RFC 3986: "Uniform Resource Identifier (URI): Generic Syntax"](https://www.ietf.org/rfc/rfc3986.txt), Section 4.2"*

**Comment by loringabriel** [comment]
Thank you @VlatkoStojkoski for clarification.
